# Generated by Django 5.0.4 on 2024-04-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_news_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='read_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
